default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: giddy_dev
  username: postgres
  password: admin

test:
  <<: *default
  database: giddy_test
  username: postgres
  password: admin

production:
  <<: *default
  <% if ENV['DATABASE_URL'] %>
  url: <%= ENV['DATABASE_URL'] %>
  <% else %>
  databse: giddy
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] %>
  username: postgres
  <% end %>
